const form=document.querySelector('#chat-form'),input=document.querySelector('#message'),messages=document.querySelector('#messages'),send=form.querySelector('button'),handoff=document.querySelector('#handoff'),themeToggle=document.querySelector('#theme-toggle'),themeIcon=themeToggle.querySelector('span'),themeColor=document.querySelector('meta[name="theme-color"]');
const supportWallet=document.querySelector('#support-wallet');
let token=localStorage.getItem('mimi_support_conversation')||'';
function applyTheme(dark){document.documentElement.setAttribute('data-theme',dark?'dark':'');themeIcon.textContent=dark?'\u2600':'\u263e';const label=dark?'Switch to light mode':'Switch to dark mode';themeToggle.setAttribute('aria-label',label);themeToggle.title=label;if(themeColor)themeColor.content=dark?'#0f172a':'#f1f5f9'}
themeToggle.addEventListener('click',()=>{const dark=document.documentElement.getAttribute('data-theme')!=='dark';localStorage.setItem('mimi_support_dark_mode',dark?'true':'false');applyTheme(dark)});
applyTheme(document.documentElement.getAttribute('data-theme')==='dark');
function add(text,type){const el=document.createElement('div');el.className='message '+type;if(type==='user'){el.textContent=text}else{const pattern=/https:\/\/[^\s]+/g;let cursor=0;for(const match of text.matchAll(pattern)){if(match.index>cursor)el.append(document.createTextNode(text.slice(cursor,match.index)));const raw=match[0],suffix=/[.,;)]$/.test(raw)?raw.slice(-1):'',url=suffix?raw.slice(0,-1):raw;const link=document.createElement('a');link.href=url;link.textContent=url;link.target='_blank';link.rel='noopener noreferrer';el.append(link);if(suffix)el.append(document.createTextNode(suffix));cursor=match.index+raw.length}if(cursor<text.length)el.append(document.createTextNode(text.slice(cursor)))}messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
async function api(method,payload){const response=await fetch('/index.php?d=api&c=ai_support&m='+method,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Support service unavailable');return data}
form.addEventListener('submit',async event=>{event.preventDefault();const text=input.value.trim();if(!text)return;add(text,'user');input.value='';send.disabled=true;try{const data=await api('chat',{message:text,conversation_token:token});token=data.conversation_token;localStorage.setItem('mimi_support_conversation',token);add(data.reply,'bot');if(data.handoff)add('Your conversation is visible to the human support team.','notice')}catch(error){add(error.message+'. Please try again or request a human agent.','notice')}finally{send.disabled=false;input.focus()}});
handoff.addEventListener('click',async()=>{if(!token){add('Send a message first so we can open a support conversation.','notice');return}handoff.disabled=true;try{const data=await api('handoff',{conversation_token:token});add(data.message,'notice')}catch(error){add(error.message,'notice')}finally{handoff.disabled=false}});
api('health',{}).then(data=>{if(data.support_wallet&&data.support_wallet_basescan_url){supportWallet.href=data.support_wallet_basescan_url;supportWallet.title=data.support_wallet;supportWallet.hidden=false}}).catch(()=>{});
